import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { IChildren } from "../interfaces/IChildren";
import HeaderAuth from "../components/auth/HeaderAuth";
import FooterAuth from "../components/auth/FooterAuth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }: IChildren,) {
  return (
    <>
      <HeaderAuth/>
      <main>
        {children}
      </main>
      <FooterAuth/>
    </>
  );
}