import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { IChildren } from "../interfaces/IChildren";
import { ILink } from "../interfaces/ILinks";
import HeaderAdmin from "../components/admin/HeaderAdmin";
import AsideAdmin from "../components/admin/AsideAdmin";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }: IChildren,) {
  const links:ILink[] = [
    { name: 'DashBoard', href: '/admin'},
    { name: 'Libros', href: '/admin/libros'},
    { name: 'Generos', href: '/admin/generos'},
    { name: 'Editoriales', href: '/admin/editoriales'},
    {name: 'Sing In', href: '/auth/login'},
    {name: 'Sing Up', href: '/auth/register'}
  ]
  return (
    <>
      <HeaderAdmin/>
      <main>
        <AsideAdmin links={links}/>
        {children}
      </main>
    </>
  );
}